Parameters:
  ExportStackName:
    Description: The name of the stack that exports the values
    Type: String
    Default: MASK

  DesiredCount:
    Description: How many instances of this task should we run across our cluster?
    Type: Number
    Default: 4

  MaxCount:
    Description: Max instances' number in the cluster
    Type: Number
    Default: 10

  MinCount:
    Description: Min instances' number in the cluster
    Type: Number
    Default: 1

  PetServiceImage:
    Description: Image in ECR
    Type: String

  DBUser:
    Type: String
    Default: master

  DBPassword:
    Type: String
    Default: petclinic

Resources:
  Service:
    Type: AWS::ECS::Service
    Properties:
      Cluster: 
        Fn::ImportValue: !Sub '${ExportStackName}-ClusterName'
      Role: !Ref ServiceRole
      DesiredCount: !Ref DesiredCount
      HealthCheckGracePeriodSeconds: 100
      TaskDefinition: !Ref TaskDefinition
      LoadBalancers:
        - ContainerName: "petclinic"
          ContainerPort: 8080
          TargetGroupArn:
            Fn::ImportValue: !Sub '${ExportStackName}-DefaultTargetGroup'


  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: petclinic
      ContainerDefinitions:
        - Name: petclinic
          Essential: true
          Image: !Ref PetServiceImage
          Memory: 450
          Environment:
            - Name: PRODUCT_SERVICE_URL
              Value:
                Fn::ImportValue: !Sub '${ExportStackName}-ProductServiceUrl'
          PortMappings:
            - ContainerPort: 8080
          Environment:
            - Name: DATABASE
              Value: mysql
            - Name: SPRING_DATASOURCE_URL
              Value:
                Fn::ImportValue: !Sub '${ExportStackName}-MasterJDBCConnectionString'
            - Name: SPRING_DATASOURCE_USERNAME
              Value: !Ref DBUser
            - Name: SPRING_DATASOURCE_PASSWORD
              Value: !Ref DBPassword
            - Name: SPRING_DATASOURCE_INITIALIZATION-MODE
              Value: always
            - Name: SPRING_DATASOURCE_CONTINUE-ON-ERROR
              Value: true
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref CloudWatchLogsGroup
              awslogs-region: !Ref AWS::Region

  CloudWatchLogsGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Ref AWS::StackName
      RetentionInDays: 7

  ServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ecs-service-${AWS::StackName}
      Path: /
      AssumeRolePolicyDocument: |
        {
            "Statement": [{
                "Effect": "Allow",
                "Principal": { "Service": [ "ecs.amazonaws.com" ]},
                "Action": [ "sts:AssumeRole" ]
            }]
        }
      Policies:
        - PolicyName: !Sub ecs-service-${AWS::StackName}
          PolicyDocument:
            {
              "Version": "2012-10-17",
              "Statement":
                [
                  {
                    "Effect": "Allow",
                    "Action":
                      [
                        "ec2:AuthorizeSecurityGroupIngress",
                        "ec2:Describe*",
                        "elasticloadbalancing:DeregisterInstancesFromLoadBalancer",
                        "elasticloadbalancing:Describe*",
                        "elasticloadbalancing:RegisterInstancesWithLoadBalancer",
                        "elasticloadbalancing:DeregisterTargets",
                        "elasticloadbalancing:DescribeTargetGroups",
                        "elasticloadbalancing:DescribeTargetHealth",
                        "elasticloadbalancing:RegisterTargets"
                      ],
                    "Resource": "*"
                  }
                ]
}

  ServiceScalableTarget:
    Type: AWS::ApplicationAutoScaling::ScalableTarget
    Properties:
      MaxCapacity: !Ref MaxCount
      MinCapacity: !Ref MinCount
      ResourceId: !Join
        - /
        - - service
          - Fn::ImportValue: !Sub '${ExportStackName}-ClusterName'
          - !GetAtt Service.Name
      RoleARN: #!Ref ECSServiceAutoScalingRoleARN
        Fn::ImportValue: !Sub '${ExportStackName}-ECSServiceAutoScalingRole'
      ScalableDimension: ecs:service:DesiredCount
      ServiceNamespace: ecs


  ServiceScaleOutPolicy:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    Properties:
      PolicyName: ServiceScaleOutPolicy
      PolicyType:  StepScaling
      ScalingTargetId: !Ref ServiceScalableTarget
      StepScalingPolicyConfiguration:
        AdjustmentType: ChangeInCapacity
        Cooldown: "60"
        MetricAggregationType: Average
        StepAdjustments:
          - MetricIntervalLowerBound: 0
            ScalingAdjustment: 2

  RequestScaleOutAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: Alarm if target has more then 100 requests/min
      ComparisonOperator: GreaterThanThreshold
      Namespace: AWS/ApplicationELB
      MetricName: RequestCountPerTarget
      Statistic: Sum
      Period: "60"
      EvaluationPeriods: "1"
      Threshold: "100"
      AlarmActions:
        - !Ref ServiceScaleOutPolicy
      Dimensions:
      - Name: TargetGroup
        Value: #!Ref DefaultTargetGroupName
          Fn::ImportValue: !Sub '${ExportStackName}-DefaultTargetGroupName'


  ServiceScaleInPolicy:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    Properties:
      PolicyName: ServiceScaleInPolicy
      PolicyType: StepScaling
      ScalingTargetId: !Ref ServiceScalableTarget
      StepScalingPolicyConfiguration:
        AdjustmentType: ChangeInCapacity
        Cooldown: "60"
        MetricAggregationType: Average
        StepAdjustments:
          - MetricIntervalUpperBound: 0
            ScalingAdjustment: -1

  RequestScaleInAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      #AlarmName: Less then 10 requests/min
      AlarmDescription: Alarm if target has less then 10 requests/min
      ComparisonOperator:  LessThanThreshold
      Namespace: AWS/ApplicationELB
      MetricName: RequestCountPerTarget
      Statistic: Sum
      Period: "60"
      EvaluationPeriods: "1"
      Threshold: "10"
      AlarmActions:
        - !Ref ServiceScaleInPolicy
      Dimensions:
      - Name: TargetGroup
        Value: #!Ref DefaultTargetGroupName
          Fn::ImportValue: !Sub '${ExportStackName}-DefaultTargetGroupName'
          
